from piccolo.apps.migrations.auto.migration_manager import MigrationManager
from piccolo.engine import engine_finder

ID = "2026-02-21T22:05:00:000001"
VERSION = "1.32.0"
DESCRIPTION = "Bootstrap production backend schema"


async def _create_schema_parity() -> None:
    engine = engine_finder()
    if engine is None:
        raise RuntimeError("Piccolo engine is not available")

    statements = [
        """
        CREATE TABLE IF NOT EXISTS category (
            id integer GENERATED BY DEFAULT AS IDENTITY,
            name character varying(100) NOT NULL,
            type text NOT NULL,
            color character varying(7),
            icon character varying(50),
            parent_category_id integer,
            created_at timestamp with time zone NOT NULL,
            order_index integer,
            CONSTRAINT pk_category PRIMARY KEY (id),
            CONSTRAINT fk_category_category_parent_category_id
                FOREIGN KEY (parent_category_id)
                REFERENCES category (id)
                ON DELETE RESTRICT
        )
        """,
        """
        CREATE TABLE IF NOT EXISTS "transaction" (
            id bigint GENERATED BY DEFAULT AS IDENTITY,
            user_id bigint NOT NULL,
            transaction_date timestamp with time zone NOT NULL,
            amount numeric(18, 2) NOT NULL,
            note character varying(500),
            category_id integer,
            tags text[] NOT NULL,
            currency character varying(100) NOT NULL DEFAULT 'AED'::character varying,
            sms_text character varying(1000),
            message_id character varying(100),
            created_at timestamp with time zone NOT NULL,
            CONSTRAINT pk_transaction PRIMARY KEY (id),
            CONSTRAINT fk_transaction_category_category_id
                FOREIGN KEY (category_id)
                REFERENCES category (id)
                ON DELETE SET NULL
        )
        """,
        "CREATE UNIQUE INDEX IF NOT EXISTS ix_category_name ON category (name)",
        (
            "CREATE INDEX IF NOT EXISTS ix_category_parent_category_id "
            "ON category (parent_category_id)"
        ),
        'CREATE INDEX IF NOT EXISTS ix_transaction_category_id ON "transaction" (category_id)',
        (
            'CREATE INDEX IF NOT EXISTS ix_transaction_transaction_date '
            'ON "transaction" (transaction_date)'
        ),
        'CREATE INDEX IF NOT EXISTS ix_transaction_user_id ON "transaction" (user_id)',
        """
        CREATE UNIQUE INDEX IF NOT EXISTS ix_transaction_user_id_message_id
            ON "transaction" (user_id, message_id)
        """,
        """
        CREATE INDEX IF NOT EXISTS ix_transaction_user_id_transaction_date
            ON "transaction" (user_id, transaction_date)
        """,
    ]
    for statement in statements:
        await engine.run_ddl(statement)


async def forwards() -> MigrationManager:
    manager = MigrationManager(migration_id=ID, app_name="db", description=DESCRIPTION)
    manager.add_raw(_create_schema_parity)
    return manager
